sudo: required
dist: trusty

language: python
python:
  - "3.6"

cache:
  pip: true
  custom_install: true

env:
  global:
  - TEST_POOL="zpool"
  - PYTEST_DATASET="pyzfsutils/tests"
  - ZDISKS_SUBDIR="zfstests"
  - ZPOOL_MOUNTPOINT="/zpool"

before_install:
  - sudo scripts/travis/ubuntu-14_04/setup_zfs_requirements.sh
  - sudo scripts/travis/common/create_test_root.sh

branches:
  only:
    - /.*/ # Build all branches

install:
  - python setup.py install
  - pip install '.[test]'

script:
  - |
    sudo env "PATH=$PATH" \
         pytest --pep8 --cov=pyzfsutils tests \
                                        --unsafe \
                                        --zpool="${TEST_POOL}" \
                                        --test-dataset="${PYTEST_DATASET}" \
                                        --root-dataset="${TEST_POOL}/ROOT/default" \
                                        --zpool-root-mountpoint="${ZPOOL_MOUNTPOINT}/root"
  - sudo zfs list
